<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Publisher\Module'                        => __DIR__ . '/Module.php',
    'Publisher\Controller\PublisherController' => __DIR__ . '/src/Publisher/Controller/PublisherController.php',
    'PublisherTest\Framework\TestCase'        => __DIR__ . '/tests/Publisher/Framework/TestCase.php',
    'PublisherTest\SampleTest'                => __DIR__ . '/tests/Publisher/SampleTest.php',
);
