<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Book\Module'                        => __DIR__ . '/Module.php',
    'Book\Controller\BookController' => __DIR__ . '/src/Book/Controller/BookController.php',
    'BookTest\Framework\TestCase'        => __DIR__ . '/tests/Book/Framework/TestCase.php',
    'BookTest\SampleTest'                => __DIR__ . '/tests/Book/SampleTest.php',
);
