<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Writer\Module'                        => __DIR__ . '/Module.php',
    'Writer\Controller\WriterController' => __DIR__ . '/src/Writer/Controller/WriterController.php',
    'WriterTest\Framework\TestCase'        => __DIR__ . '/tests/Writer/Framework/TestCase.php',
    'WriterTest\SampleTest'                => __DIR__ . '/tests/Writer/SampleTest.php',
);
